### ISSUE TITLE
Add support for optionally invoking a AS Refresh

### ISSUE THREAD

**Issue by alexmarshall132** [liprec/vsts-release-aas#1]
Would it be possible to add an option to the Azure Analysis Services Deployment step to invoke a refresh on the data model after the deployment completes successfully ?

**Comment by liprec** [comment]
You can add the task 'Execute TSML Script' to your release pipeline and use a Refresh script (https://docs.microsoft.com/en-us/sql/analysis-services/tabular-models-scripting-language-commands/refresh-command-tmsl) to process the model.
