### ISSUE TITLE
Cannot connect to server. Client with IP Address x.x.x.x is not allowed to access the server

### ISSUE THREAD

**Issue by rhlgupta1383** [liprec/vsts-release-aas#10]
Deployment task is not able to bypass the firewall using the hosted agent (cant be whitelisted in firewall since the hosted agent IP is dynamic)

**Comment by liprec** [comment]
This is a generic issue with hosted agents and the firewall with Azure Services.
At this moment there is no option to enable Azure Services access to AAS in a generic way. The only option is to add all the IP ranges of the used datacenter to the firewall.

See https://azure.microsoft.com/en-us/blog/hardening-azure-analysis-services-with-the-new-firewall-capability/ for more information.

**Comment by liprec** [comment]
I just released a minor version (v1.2) with Firewall support.
