### ISSUE TITLE
Login type - Inherit from connection

### ISSUE THREAD

**Issue by inteligenciaacademica** [liprec/vsts-release-aas#105]
I'm trying to use the component in the Azure pipeline with Login type Inherit from connection , but it returns the following error(##[error]Cannot bind argument to parameter 'String' because it is null.
) .
I can not understand

`##[debug]Processed: ##vso[task.logissue type=warning]The 'tsmlScript' option will be deprecated in a future version.
##[debug]INPUT_TSMLSCRIPT (empty)
##[debug]INPUT_TMSLFOLDER: 'D:\a\1\s'
##[debug]INPUT_IPDETECTIONMETHOD: 'autoDetect'
##[debug]INPUT_DELETEFIREWALLRULE: 'true'
##[debug] Converted to bool: True
##[debug]Loading module from path 'D:\a\_tasks\execute-aas-tsml_92d41ce5-204b-4284-8caf-9920225e9d01\1.5.8\ps_modules\VstsAzureRestHelpers_\VstsAzureRestHelpers_.psm1'.
##[debug]$OVERRIDING $global:DebugPreference from 'Continue' to 'SilentlyContinue'.
##[debug]Loading resource strings from: D:\a\_tasks\execute-aas-tsml_92d41ce5-204b-4284-8caf-9920225e9d01\1.5.8\ps_modules\VstsAzureRestHelpers_/module.json
##[debug]Loaded 11 strings.
##[debug]SYSTEM_CULTURE: 'en-US'
##[debug]Loading resource strings from: D:\a\_tasks\execute-aas-tsml_92d41ce5-204b-4284-8caf-9920225e9d01\1.5.8\ps_modules\VstsAzureRestHelpers_\Strings\resources.resjson\en-US\resources.resjson
##[debug]Loaded 11 strings.
##[debug]Loading module from path 'D:\a\_tasks\execute-aas-tsml_92d41ce5-204b-4284-8caf-9920225e9d01\1.5.8\ps_modules\TlsHelper_\TlsHelper_.psm1'.
##[debug]Loading resource strings from: D:\a\_tasks\execute-aas-tsml_92d41ce5-204b-4284-8caf-9920225e9d01\1.5.8\ps_modules\TlsHelper_/module.json
##[debug]Loaded 3 strings.
##[debug]SYSTEM_CULTURE: 'en-US'
##[debug]Loading resource strings from: D:\a\_tasks\execute-aas-tsml_92d41ce5-204b-4284-8caf-9920225e9d01\1.5.8\ps_modules\TlsHelper_\Strings\resources.resjson\en-US\resources.resjson
##[debug]Loaded 3 strings.
##[debug]Exporting function 'Add-Tls12InSession'.
##[debug]Exporting function 'Assert-TlsError'.
##[debug]Importing function 'Add-Tls12InSession'.
##[debug]Importing function 'Assert-TlsError'.
Added TLS 1.2 in session.
##[debug]Exporting function 'Add-AzureSqlDatabaseServerFirewallRule'.
##[debug]Exporting function 'Remove-AzureSqlDatabaseServerFirewallRule'.
##[debug]Exporting function 'Get-AzStorageKeys'.
`

**Comment by liprec** [comment]
Thanks for the feedback: is the service connection configured to use a SPN or a client certificate?

**Comment by inteligenciaacademica** [comment]
thanks for quickly answer. 
I resolved for other method .
Well maybe  than    understand wrong the  function this method "Inherit from connection" .
I thought this method would use my authentication with Azure login
