### ISSUE TITLE
Unreachable Network -> Socket Error

### ISSUE THREAD

**Issue by OlavRab** [liprec/vsts-release-aas#108]
When deploying a model via a release pipeline, I get the following error:

 ##[error]System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A socket operation was attempted to an unreachable network 169.254.169.254:80

Any idea what could go on? Does this have to do with the Database connection? Or the AAS-Connection?

Thanks!

**Comment by liprec** [comment]
Is it possible you are using a service connection using a managed identity? If yes: this authentication scheme is not supported and you can switch and use a service principal.

**Comment by OlavRab** [comment]
I'm not entirely sure. But in my Azure portal, I open "Enterprise Applications" and it will show under the type "Enterprise Application", not Managed Identity.

**Comment by liprec** [comment]
If you go to the `Project Settings` -> `Service Connections` and select the connection you are using: does it say: `using service principal authentication`?
