### ISSUE TITLE
Unable to add Azure Analysis task to the pipeline

### ISSUE THREAD

**Issue by KristofKuli** [liprec/vsts-release-aas#111]
I have installed Azure Analysis Service to our organization, but I am unable to add it to the pipeline. Instead of Add button, I just have a button which displays "Installed" and I am not able to click on it.
![image](https://user-images.githubusercontent.com/103577855/186642592-40dec200-f7e1-43fa-86d1-5f3ee7b0b77a.png)

Can you please advise what can be done? I have already reinstalled the extension, but it didn't solve the issue.

**Comment by liprec** [comment]
Hi @KristofKuli,

After you installed the extension, you can add the included tasks (`TMSL Script` and `Tabular Database Deployment`) to your pipeline: the top two tasks in your screenshot.

-JP

**Comment by kazi-sabbir** [comment]
@KristofKuli : 
Did you check if you have Task Restrictions set on your DevOps Org settings to "Disable Marketplace Task"?

![image](https://user-images.githubusercontent.com/3162132/191554279-9e49a278-5340-49a9-9901-1f93e88e3084.png)
