### ISSUE TITLE
At this moment depoying a model via a SPN is not yet supported. I am in the process of rewriting all my VSTS extensions to NodeJS to be platform independent (and the are running faster) and it will include the deployment with SPNs, but it will take a little bit longer.

### ISSUE THREAD

**Issue by paulomatiolimosaic** [liprec/vsts-release-aas#12]
Jan, is this already fixed? Can we deploy using SPN ?

At this moment depoying a model via a SPN is not yet supported. I am in the process of rewriting all my VSTS extensions to NodeJS to be platform independent (and the are running faster) and it will include the deployment with SPNs, but it will take a little bit longer.

So at this moment you need an user and that user needs to be service admin to be able to deploy a model to AAS. And with the new version this user can be changed to an SPN, because you need access to both the Azure resource and the service itself.

(Duplicate of #5)

_Originally posted by @liprec in https://github.com/liprec/vsts-release-aas/issues/11#issuecomment-404234171_

**Comment by jublair** [comment]
Appears to be no updates since last year. Our org also disallows app passwords/non-MFA logins, so SPNs are the only way I can get this to work. Any updates on this?

**Comment by garimasingh15** [comment]
Even though I am an Analysis Services Admin on the Azure Portal, I am unable to deploy data models using the Azure Analysis Service Deployment task. The error I am encountering is, "**##[error]Error during deploying the model (The property 'database' cannot be found on this object. Verify that the property exists and can be set.)**"
Any help would be appreciated.

**Comment by liprec** [comment]
I just released a minor version (v1.2) with Service Principal support.

@garimasingh15, can you open a new issue as I do think that it is not related to Service Principal support. Looks to me that the `.bim` is not correct.

**Comment by jublair** [comment]
Thanks @liprec! However I think that there's a misconfiguration with the task - when you select the 'service principal' option on the task and fill in the fields, I get an error saying that some settings need attention. Changing the login type back to 'named user' and filling in those fields make the error go away. Are the named user fields being marked as optional if they're hidden?

**Comment by liprec** [comment]
@jublair: as far as I know it is working if you start with a new task. So probably there is still some in the input boxes that triggers the task validation due to switching from 'named user' to 'service principal'.
