### ISSUE TITLE
deprecation warnings

### ISSUE THREAD

**Issue by NickA01** [liprec/vsts-release-aas#121]
HI, 
We've been running this for some time now but have noticed several warnings re deprecation. 

Any ideas regarding when these will actually be deprecated and also what is generating the warning-I can't see these anywhere within the code base so guessing they are outputs from the API's?

![image](https://user-images.githubusercontent.com/91599322/228491799-87a44eaf-40bf-4688-a208-bf9c375a3002.png)

Thanks

**Comment by liprec** [comment]
Currently I do not have any timelines for when these options will be dropped.

For the `tsmlScript` option, the check is at the line https://github.com/liprec/vsts-release-aas/blob/329075db4671e35280e5ef992afb69edd22456d0/execute-aas-tmsl/v1/execute-aas-tmsl.ps1#L29

But the warning should be gone if you use the `tmslScript` option.

**Comment by NickA01** [comment]
Jan,  thanks very much for the quick reply. 
Many thanks
