### ISSUE TITLE
Exception calling "DeserializeDatabase" with "1" argument(s): "Unrecognized JSON property: maxParallelismPerRefresh

### ISSUE THREAD

**Issue by jashwood** [liprec/vsts-release-aas#122]
What compatibility version does this extension support? 
maxParallelismPerRefresh is a newer Model property, are you able to update the version of AMO being used? 
maxParallelismPerRefresh was introduced in compatibility level 1568 which was quite some time ago, we are at 1601 now I believe.
Thanks
Josh

**Comment by liprec** [comment]
The latest version (v1.5.11) contains a change that should solve this issue.
