### ISSUE TITLE
Add Support for Deployment of Field Parameters

### ISSUE THREAD

**Issue by OlavRab** [liprec/vsts-release-aas#123]
Hi, I've added field parameters trough the following Calculated Table:

![image](https://github.com/liprec/vsts-release-aas/assets/38460642/16f79601-27dd-4910-8612-2a882478de98)

I used a script from the Tabular Editor Builder: https://github.com/TabularEditor/TabularEditor3/issues/541#issuecomment-1129228481

But once I use your extention to deploy via DevOps, I get the following error:

2023-05-10T14:28:29.5843910Z ##[error]Not a valid model file. (Exception calling "DeserializeDatabase" with "1" argument(s): "Unrecognized JSON property: relatedColumnDetails. Check path 'model.tables[19].columns[0].relatedColumnDetails', line 1, position 335653.")

The Field Parameters Adds a new property to the model: "RelatedColumnDetails', apparently the extention does not yet understand this!

Thanks!

**Comment by liprec** [comment]
The latest version (v1.5.11) contains a change that should solve this issue.

**Comment by OlavRab** [comment]
Yes, it has been updated and works now. Thanks!

**Comment by liprec** [comment]
Thanks for the confirmation!
