### ISSUE TITLE
Issue after firewall deploy - unable to login for deploy

### ISSUE THREAD

**Issue by shanerisk** [liprec/vsts-release-aas#13]
I'm trying to set up an AAS deploy using this extension and I'm getting the following errors.  Its configured to deploy with a named user who is configured as an AAS admin.

ERROR:
Error during adding automatic firewall rule (Authentication failed: User ID and Password are required when user interface is not available.)

Authentication failed: User ID and Password are required when user interface is not available.

**Comment by liprec** [comment]
New version (v1.2.1) is available via the marketplace

**Comment by shanerisk** [comment]
Thanks, I will try it out!
