### ISSUE TITLE
Tasks missing in Azure DevOps

### ISSUE THREAD

**Issue by simondmorias** [liprec/vsts-release-aas#15]
Hi I have today installed this plugin into our Azure DevOps. It says deployed but no tasks are available:
![image](https://user-images.githubusercontent.com/12765000/55080993-f8bd9000-5096-11e9-8b2a-45545a61bf5f.png)

You can see in that screenshot it has installed. But I can't find any tasks???

**Comment by liprec** [comment]
Can you take a look, if allowed, if the extension is also installed in the 'Extensions' section of the 'Organization Settings' : https://dev.azure.com/<organization>/_settings/extensions?tab=Manage&status=active

**Comment by simondmorias** [comment]
Thanks for the response. These have "appeared" overnight. I suspect some issues on the Microsoft side. Closing this issue.
