### ISSUE TITLE
Refresh TMSL Not Working

### ISSUE THREAD

**Issue by maaldo** [liprec/vsts-release-aas#16]
Thank you for a great plugin!

I have successfully been able to deploy my model to the AAS instance via the Deployment task with all AAS, auth, and sql connection information configured. In addition to the deployment, I've been able to verify within SSMS that the model and associated sql connection is there within my AAS instance.

The next task in the release pipe executes a Refresh TMSL script and this is where I am running into issues. The TMSL task has the requisite AAS, and auth configured as well as an inline TMSL script. Here is the basic script I'm trying to execute to refresh the data:

{
    "refresh": {
        "type": "full",
        "objects": [
            {
                "database": "MY_MODEL"
            }
        ]
    }
}

I have also tried different permutations with override values but nothing seems to work. This is the error I'm getting:

The JSON DDL request failed with the following error: Failed to execute XMLA. Error returned: 'The given credential contains a property with a null value. Data source kind: SQL.  Property name: EncryptConnection. . The exception was raised by the IDbConnection interface.

Any guidance you could provide would be incredible thank you!

**Comment by liprec** [comment]
Can you manual refresh the model via SSMS? Looks to me that the credentials to the datasource are somehow not correct.

**Comment by maaldo** [comment]
Thank you for the response. I've tried both a sql server admin account and the user/pw credentials our application uses in the connection string, but both result in the same error.

Both accounts are Azure Active Directory users however. Is there something in addition to the "Source User Login" other than USER@MY_DOMAIN.COM that must be specified if it is an AD account?

The AAS admin account I use to deploy the model is also an AD account and I have not had a problem with that task.

**Comment by maaldo** [comment]
Thanks for the help Jan. Looks like this is an issue with the datasource connection as I can't even execute that TMSL from SSMS after it has been deployed.

**Comment by maaldo** [comment]
I believe this is an issue with the model definition within the JSON. Would you have an example model that can be used with both deploy and TMSL tasks that I could possibly compare against? Still getting this issue.

**Comment by felipeabd** [comment]
any solution to this issue? i have a similar problem. I do the deployment but I need to update the data to complete the task, I get a connection failure problem when updating. it only works if I run data tools. nor by ssms it works. can you help me?
