### ISSUE TITLE
Error Adding firewall rule

### ISSUE THREAD

**Issue by samboot7** [liprec/vsts-release-aas#18]
Using version 1.2.5 
When deploying to azure analysis services receiving the error shown below when using "auto detect" in the firewall rules configuration.
![AutoDetectIP](https://user-images.githubusercontent.com/19488677/55428516-24ea7c80-5581-11e9-986f-fde58f9d89bf.PNG)
When specify an IP range the following error is received
![DefinedIPRange](https://user-images.githubusercontent.com/19488677/55428629-5f541980-5581-11e9-9323-d7cedd595b1c.PNG)

**Comment by liprec** [comment]
Can you try adding a variable `system.debug` and set it to `true` to enable debug logging so I can identify what is causing this error.

**Comment by samboot7** [comment]
Debug logging as requested
[tasklog_9.log](https://github.com/liprec/vsts-release-aas/files/3040345/tasklog_9.log)

**Comment by liprec** [comment]
Thanks for the logging. Can you check if the password doesn't contain any quote `'` or `"`?
It looks like that is causing the issue and the task doesn't escape special connection string or PowerShell characters.

**Comment by samboot7** [comment]
The password did contain `"`.  I have updated the password and now everything is working as expected.  Thanks.
