### ISSUE TITLE
Analysis Service Deployment using Auth Authentication

### ISSUE THREAD

**Issue by Xiadre** [liprec/vsts-release-aas#20]
I am deploying a tabular model from one environment to another via VSTS, where I want to modify the data source connection in the <model_name>.asddatabase and the auth credentials (tokens). My data source is Azure Datalake. 

When deploying from one environment to another manually and modifying the data source connection so that the model points to the new Datalake, we get a prompt to enter the credentials for that particular datalake data source. Once we authenticate,the credentials of the model for that analysis service gets refreshed as new tokens are generated on oauth.

Question: Is there any way to modify the data source connection of a bim file and authenticating it simultaneously when deploying to a new env

**Comment by garimasingh15** [comment]
@liprec I am facing the same issue. Any help on how to go about handling this would be appreciated.

**Comment by liprec** [comment]
At this moment the deploy task only supports connections to Azure SQL Databases/Datawarehouse via an username/password combination. I will add this as a feature in a new version.

**Comment by cpatte7372** [comment]
Hello liprec, do you have an ETA when the feature will be added?

Cheers
Carlton
