### ISSUE TITLE
Retain Roles & Members

### ISSUE THREAD

**Issue by Mahahaleel** [liprec/vsts-release-aas#21]
Hello,

First of all, thank you very much for this great functionality!
I do have a question that would help our deployments greatly:
Is it possible to support the "Retain Roles & Members" functionality present in the deployment wizard?
These deployment options are part of a separate file during deployment (model.deploymentoptions). 
Currently all roles and members are overwritten during deployment to the target server and have to be reset afterwards.

Regards,

Nick de Korte

**Comment by liprec** [comment]
At this moment it is not possible, but thanks for the suggestion and I will add it in a future version.

**Comment by vmsyadav** [comment]
Hello liprec,

  I appreciate and Thanks for the Azure Devops Task for Azure Analysis Service.
Even I am in need of the "Retain Roles & Members" functionality in the task, is there any possibility to get that functionality soon.Thanks in Advance

**Comment by sushantppotdar** [comment]
Hi liprec,

Thanks for making this task for SSAS deployment.

I am too working on SSAS deployments with roles for each environments (DEV, UAT and PROD). 
As a workaround I am deploying the roles using TMSL scripts but it is getting more complex as it is development overhead to separate out roles from Model.bim.

Please can you add functionality to get control on Roles and Members while deployment, would be much helpful.

Regards
