### ISSUE TITLE
##[error]Error during deploying the model (A semicolon was expected at index 158 in the connection string.)

### ISSUE THREAD

**Issue by erikatgaia** [liprec/vsts-release-aas#22]
Hi!
I use the pipeline task for deploying AAS db and I'm deploying a tabular model with an Azure SQL Data Warehouse-data source.
I get the following error message:
##[error]Error during deploying the model (A semicolon was expected at index 158 in the connection string.)

I have no control over the connection string (and is it connection string to AAS or to the data source?). Any ideas of what is wrong?

Erik

**Comment by liprec** [comment]
Is it possible that the password for the Azure SQL DataWarehouse contains a ';', '=' or any quote character? That could cause an error when constructing the needed connectionstring for the Azure DWH connection.

**Comment by erikatgaia** [comment]
Yes, you are problably right, I cannot see the password but I solved it through adding simple quotation mark around the variable containing the password, e.g. '$(pwdVariable)'
