### ISSUE TITLE
Error during deploying the model (The property 'database' cannot be found on this object. Verify that the property exists and can be set.)

### ISSUE THREAD

**Issue by otaconwow** [liprec/vsts-release-aas#23]
Hello,

I'm trying to change the data source from my model when deploying it, but I'm getting this error whenever I try.

Any help?

**Comment by liprec** [comment]
What error do you get?

**Comment by otaconwow** [comment]
I was getting the message "Error during deploying the model (The property 'database' cannot be found on this object. Verify that the property exists and can be set.)" when I specified a different data source in the task. But i managed to make it work recreating the task when setting the data source to "Azure SQL" right away. It seem that, if I set the data source type to "None" then execute the pipeline, and change it afterwards, the problem happens. But for now, everything is ok, thanks for the response.
