### ISSUE TITLE
$PSEdition not set

### ISSUE THREAD

**Issue by jaspalsundal** [liprec/vsts-release-aas#24]
deploy fails with the error message ##[error]The variable '$PSEdition' cannot be retrieved because it has not been set, i get this error message regardless if i choose "use latest installed version" option or if i specify a specific version such as "2.0.0"

**Comment by liprec** [comment]
I just tried the deploy task myself and I didn't encounter any errors, so maybe you can recreate the task to see if the error disappears.

**Comment by ckupferschmid** [comment]
hi
I'm having the same issue here.
any advice?

**Comment by maaldo** [comment]
I also experienced this issue using the Hosted agent pool. If we are required to use the Hosted agent pool is there a way around this issue? Perhaps even providing this variable in the release pipe itself? What value should it be set to?
