### ISSUE TITLE
Cannot bind argument to parameter 'RolloutEnvironment' because it is null.

### ISSUE THREAD

**Issue by kesselschlaeger** [liprec/vsts-release-aas#25]
Hello,

we try to create a release pipeline for an AS Deployment.
for authentication we use a service principal. in this case we get the error:
Cannot bind argument to parameter 'RolloutEnvironment' because it is null.
i think you use an older azure powershell library?

any ideas?
Best regards
André

**Comment by liprec** [comment]
The tasks has all the needed Powershell modules included and I just tried the deploy task myself and I didn't encounter any errors, so maybe you can recreate the task to see if the error disappears.

**Comment by LValla** [comment]
Hello @kesselschlaeger, did it work to you in the end? I'm getting this error for the first time after using this package many times in the past.
I'm wondering if there are any problems with the RolloutEnvironment variable that is behind the scene but that we cannot set in the package
thanks a lot

**Comment by ChristinaHolmes** [comment]
I am receiving this same error, but only when deploying using the Service Principle. Is there a workaround or a way we can setup this parameter in the deployment task?

**Comment by liprec** [comment]
Hi All,

Sorry for the ignorance on my side, but looking at this issue I misjudged it in the first place.
The only reference to `RolloutEnvironment` is when it is extracted from the `ServerName` parameter of the task. Is this set correctly, like `asazure://westeurope.asazure.windows.net/fabrikam`?

-JP

**Comment by ChristinaHolmes** [comment]
Bingo! That was my issue, I had the incorrect server name. Once fixed everything deployed.

Thank you for this package!
