### ISSUE TITLE
Deploy to Gov Cloud Azure Analysis Services

### ISSUE THREAD

**Issue by kingua** [liprec/vsts-release-aas#34]
Do you know if this should work deploying to Azure Analysis Services in Gov Cloud?  When we try to do so, we get the error: Unknown Analysis Services environment name specified.

We have confirmed the pathing, names, and service account permissions are correct.

Thanks!

**Comment by liprec** [comment]
I have never tested it as I have no access to any of the Gov Clouds, but I cannot see any reason why it should not working.
Is it possible to share more details?

**Comment by kingua** [comment]
No matter what, we always get the error "Unknown Analysis Services environment name specified".  Unfortunately, there's not a lot of helpful info in the logs, even with debug turned on in the pipeline.

We have noticed that a lot of things in Gov Cloud don't work like they do in Commercial Cloud.  We had to jump through hoops to AzDO to connect to Azure Data Factory and also are having connectivity issues with Power BI in Gov Cloud.

I'm wondering if this is just another case of things either not being mature in Gov Cloud or simply differences with the way Gov Cloud authenticates.  It's very hard to find Gov Cloud specific information.

I was just wondering / hoping you had run into the issue and might have had some idea of what is happening.

Thanks!

**Comment by kingua** [comment]
The error happens on line 321 in deploy-aas-db.psm1.

So, it seems there is a problem with the Credential.  We made sure to add the Service Principal the Server Admin role in AAS via SSMS.  Unless there's some other place we need to add permission(s), it seems that it's just a Connectivity issue specifically w/ Gov Cloud :(

**Comment by kingua** [comment]
Or maybe it's an AzureRM vs Az issue?
