### ISSUE TITLE
Issue with existing firewall Rule causing exceptions

### ISSUE THREAD

**Issue by persistence911** [liprec/vsts-release-aas#35]
When using the task there are instances where the firewall was created  on the analysis services. On failure the firewall does not get removed  from analysis. 

This scenario causes an issue where when rerunning the task it tries to put in the firewall again and it fails when it checks and finds out the firewall name already exist. 

I am happy to open a PR for this issue and fix this because I think checking if it exist already and updating if it does will work in this scenario, given the name has to be vsts-release-aas. 

Also adding in error handling into the code might help revert the firewall when an exception occurs during processing for instance.

**Comment by liprec** [comment]
Sorry for the late response and indeed there should be an extra check upfront to remove any left overs of previous runs.
Will add it to a next release anytime soon.
