### ISSUE TITLE
Replica / scale-out support

### ISSUE THREAD

**Issue by lukerosser** [liprec/vsts-release-aas#36]
https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-scale-out#connections

As per the above, when using scale-out there are two different server names - one for management and one for end users. In the current task a server name is provided which is used for both deployment, and updating the firewall. The management server name has :rw appended and doesn't match the resouce name in Azure so the firewall update fails.

Currently this task **requires** that the firewall be updated on deployment so the only way to successfully deploy when using replicas is to enable "continue on error" and not set the firewall when deploying as it will error.

Would it be possible to look at adding a setting for deploying against replicas? This can automatically append :rw where relevant in the task.

Another useful addition to consider is an optional a sync to the replicas after the model is deployed.

**Comment by liprec** [comment]
Thanks for the feedback and I will take a look in how to support these kind of scale-out scenarios.

**Comment by yorickbouma** [comment]
Had not seen this issue but I have created issue #43 for this and PR #42.

**Comment by liprec** [comment]
I just uploaded v1.3.2 which contains your PR. Please validate if it is working as expected.
