### ISSUE TITLE
The JSON DDL request failed with the following error

### ISSUE THREAD

**Issue by lucifer147** [liprec/vsts-release-aas#39]
I've got this error, i also changed the whole name without any characters but still failed. if there are cool guys could help me?

The 'Name' property cannot contain any of the following characters: . , ; ' ` : / \ * | ? " & % $ ! + = ( ) [ ] { } < >.  Technical Details: RootActivityId: ebfea9b0-e752-4ce5-ab52-adc2093fa50f Date (UTC): 5/11/2020 8:18:28 AM (ErrorCode: -1055784777)

**Comment by liprec** [comment]
This is probably a limit of Azure Analysis Service and the database name, so unfortunately I cannot change this behavior.
But I will add an extra validation and some proper error message to the name value

**Comment by Toerstad** [comment]
I'm getting the exact same error. Does anyone know what 'name' the error refers to? My model name do not have any special characters.
