### ISSUE TITLE
Deployment of asdatabase/bim file fails

### ISSUE THREAD

**Issue by Bindsi** [liprec/vsts-release-aas#4]
Hi,

my name is Marcel Bindseil, working for Microsoft Germany.
At our client we use AAS and want to automate deployment process.
So I stumpled over your great VSTS extension but I don´t get it run.

I have tried to deploy the attached asdatabase or bim file. Neither the as database nor the bim file worked for me.
I also attached the task configuration in VSTS release definition.
[vststask1](https://user-images.githubusercontent.com/16034499/32625899-ecf50856-c58d-11e7-90d7-5c3909bf09f6.png)
[vststask2](https://user-images.githubusercontent.com/16034499/32628633-d379c4b2-c596-11e7-8985-28d3589e7dfb.png)

[asdatabase.txt](https://github.com/liprec/vsts-release-aas/files/1458954/asdatabase.txt)
[bim.txt](https://github.com/liprec/vsts-release-aas/files/1458955/bim.txt)

Deployment Task just returning:
`2017-11-09T19:15:02.9454304Z ##[command]Import-Module -Name C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Profile\AzureRM.Profile.psd1 -Global
2017-11-09T19:15:03.3624369Z ##[command]Add-AzureRMAccount -ServicePrincipal -Tenant ******** -Credential System.Management.Automation.PSCredential -EnvironmentName AzureCloud
2017-11-09T19:15:04.7292901Z ##[command]Select-AzureRMSubscription -SubscriptionId 4025db3d-bb6f-4de1-8485-36a843f29882 -TenantId ********
2017-11-09T19:15:05.4500959Z ##[error]Error during deploying the model (The property 'database' cannot be found on this object. Verify that the property exists and can be set.)
2017-11-09T19:15:05.4700937Z ##[section]Finishing: Deploy model to asazure://westeurope.asazure.windows.net/sppdefaultasdev01`

Another company I know is using the same asdatabase file structure and there it works
´{
  "name": "Evobus Telemetry Data Model",
  "compatibilityLevel": 1400,
  "model": {
    "name": "Evobus Data Model",
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/evobussqldev01 database windows net;telemetrydb",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "evobussqldev01.database.windows.net",
            "database": "telemetrydb"
          },
          "authentication": null,
          "query": null
        },
…..
´
Can you help to investigate?

Thanks,
Marcel Bindseil
Microsoft Modern Apps Consultant

**Comment by liprec** [comment]
What you can try is to disable the 'Remove before Deploy' option: I see a reference in the code to that error message in the corresponding method. If that is not solving the issue, can you add the variable `system.debug` and the value `true` to the pipeline? This will provide more detailed logging and hopefully also the line number when the error is raised.

And as another thing: please change the database password as your vstask2 screenshot contains the password. You can also contact GitHub to physically remove the file.
A better sustainable solution is to use secure variable for passwords

**Comment by Bindsi** [comment]
Yeah, of course.

In the meanwhile I already read your code and figured out what you mentioned.
I unchecked "Remove before Deploy" and "Overwrite" and now it is working.
Thanks for your support. Very appreciated

**Comment by liprec** [comment]
I will change the error message that is returned by the 'remove' method as it is not clear.
Thanks for the update.
