### ISSUE TITLE
Issues with Pipeline Variables

### ISSUE THREAD

**Issue by jazminelich** [liprec/vsts-release-aas#41]
I am currently creating release pipelines using this tool in order to deploy data models to Azure Analysis Services using Azure Repos Git. When I go through the fields for connection information and input usernames/passwords in plain text directly in those fields, the release runs fine and succeeds. When I attempt to set pipeline variables to use these passwords without storing in plain text, I find that it is not actually using those variables. A common error I receive is that an invalid client secret was provided. If I put that client secret in plain text on the tasks option, then it works fine. It is only if I attempt to use it as a variable that is supposed to be locked. I'm not sure if anyone else has run into this issue or if I am doing something wrong, but it would be beneficial to be able to use the pipeline variables for passwords and such. 
Thank you!

**Comment by liprec** [comment]
As far as I know the task should be able to process secret variables.
Is this also the case with other tasks, eg https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables?

**Comment by liprec** [comment]
You are correct that you cannot retrieve the secret by 'unlocking' it: the value is empty.
And secrets are only hidden for the user output/log and not for the tasks itself. The only thing I can think of is that there are characters in the password that are not correctly parsed by PowerShell.
Can you change the password to one without any special characters?

**Comment by jazminelich** [comment]
That would make sense. Unfortunately, I am not able to change most of these passwords, but I did notice this when I looked at the YAML, so it does look like it's not recognizing the variables. 
![image](https://user-images.githubusercontent.com/66683250/84403601-8073b980-abcb-11ea-9032-6f6e44752ce9.png)
