### ISSUE TITLE
Az Support

### ISSUE THREAD

**Issue by ThomasMey123** [liprec/vsts-release-aas#44]
Hi Jan Pieter, so you intend to support the Az Module in the near future?

**Comment by vdev469** [comment]
It will be good if this task supports Az. Currently it only supports AzureRM 2.1.0 PS version

**Comment by vani353** [comment]
@liprec any update on this feature?

**Comment by liprec** [comment]
Sorry, probably not. I intent to move the task to NodeJS/JavaScript for the next version, which should solve a lot of combability issues.
