### ISSUE TITLE
Multiple source Databases 

### ISSUE THREAD

**Issue by bmnyc0923** [liprec/vsts-release-aas#45]
Hi ,
Thanks for your great work but i have a question or maybe an issue on the extension . My AAS model has three different servers connected to it . but the extension only allows be to input 1 so it always fails . Can you please help me how do i declare multiple source Databases 

Thankyou

**Comment by TrailRunner23** [comment]
Hi, I am also looking to deploy a Model connected to multiple sources. Any solution to the issue yet?
