### ISSUE TITLE
Deploying using a Service principal

### ISSUE THREAD

**Issue by simzei** [liprec/vsts-release-aas#5]
I would like to run the deployment using a service principle. I've tried different ways of passing the credential information, using AppId, ObjectId, and the app:AppId@TenantId. All of these options lead to an error "Error during deploying the model (Exception has been thrown by the target of an invocation.)".

I've looked in the code and I see that you do not use "Login-AzureAsAccount". Using this commandlet is the only way that I manage to get these database level commandlets working with my service-principal. Are you considering adding support for service principals / apps?

**Comment by liprec** [comment]
Good suggestion and I will add it to the extension.

**Comment by niya90** [comment]
Hi , Is the SPN login is added to the code?

**Comment by liprec** [comment]
It is not yet added, but I will add it anytime soon, but no ETA yet.

**Comment by isehuet** [comment]
Just posted an issue which is most likely related to the above enhancement. Would really like this enhancement, we are running the CI/CD over VSTS using SPN as well.

**Comment by liprec** [comment]
I just released a minor version (v1.2) with Service Principal support.
