### ISSUE TITLE
error during adding automatic firewall rule

### ISSUE THREAD

**Issue by MichaelGarrido2** [liprec/vsts-release-aas#54]
I get the following error when I'm trying to publish an azure analysis services model:

Error during adding automatic firewall rule (Unable to obtain authentication token using the credentials provided. If your Active Directory tenant administrator has configured Multi-Factor Authentication or if your account is a Microsoft Account, please remove the user name and password from the connection string, and then retry. You should then be prompted to enter your credentials.)

_Any ideas what's wrong?_

I've looked through both the opened and the closed issues, but no issue seem to have my problem

I'm using the Login Type=Named User

**Things I've tested:**
- I've verified that the account used can connect to the model and is admin on the azure analysis service.
- the account doesn't require MFA (Tested by connecting from SSMS)
- I've tested both turning the firewall on and off
- I've added the system.debug = true variable in the pipeline 
- Regular publish from VS works fine

**Comment by MichaelGarrido2** [comment]
I got the deployment to pass. We where using Developer pricing tier on AZ AS, so I changed it to basic or rather to standard since we're using perspectives...
Seems like the firewall rule stuff only applies to pricing tier Basic or higher. We are using Developer for development, but in this pricing tier the firewall feature isn't available (I guess?). 
Could the extension take this into account so that it's possible to disable the firewall rule add/delete with an option?

**Comment by liprec** [comment]
If your Analysis Service admin has MFA enabled, the pipeline cannot run unattended as the MFA expects a user interaction.
It is better to add a service principal as Analysis Service admin and use those app id/secret to login and deploy the new model.

**Comment by MichaelGarrido2** [comment]
@liprec  Thanks for a quick reply.
We've fixed the MFA problem. They had a special policy that require MFA for login made from other countries than their countries where they are engaged, so that is sorted out.
I will re-test deployment against an azure analysis service in Dev tier, and will add an issue if there is a problem with that or have you tested to deploy to a D1 pricing tier?
we can close this issue, after your feedback on the D1 tier deployment.

**Comment by liprec** [comment]
It works for D1 tiers as this is the tier I am using to test my tasks due to costs 😉.
And indeed re-open this issue if you are still having issues.
