### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by AlexMechanicus** [liprec/vsts-release-aas#57]
Hello there!

Deployment failed with the following error:
2021-03-22T13:27:05.8396031Z ##[error]Cannot add a member with the name "Password" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to your command.

I see that was added else block with the following statement:
$connectionStringJSON | Add-Member -name "Password" -Value $Password -MemberType NoteProperty

According to if statement we shouldn't jump into ELSE block, because our connection is set as Provider.

How we can fix or avoid this issue?

**Comment by liprec** [comment]
Looks like the connection string in the BIM file contains already a password element. Can you validate for me? And to solve it from your end is to remove the Password element.
In a next version I will add the Force parameter to make sure that it will succeed.

**Comment by AlexMechanicus** [comment]
Hi Jan Pieter,

Yes, in our CI/CD pipeline we have PowerShell Script which replace wildcard connection string value by actual connection string, like this:
$filePathName="$(TabularModelName)"
$JSON = Get-Content $filePathName | Out-String | ConvertFrom-Json
$JSON.model.datasources[0].connectionString="$(DwhConnectionString)"
$JSON | ConvertTo-Json -Depth 100 | Out-File $filePathName

Ok, let me try to remove Password from connection string variable.
I will keep you posted.
Thanks!

**Comment by liprec** [comment]
But if you replace the connection string settings yourself, you can set the `connectionType` setting to `none` to prevent the task to do the same.
But the latest version now supports legacy datasources, so you can also remove your custom PoSh script and let the task set the connectionstring.

**Comment by AlexMechanicus** [comment]
Sure, thanks for help! 
Will check and let you know.

**Comment by AlexMechanicus** [comment]
All works! Thanks a lot!
