### ISSUE TITLE
Question: Use with Power BI Premium

### ISSUE THREAD

**Issue by dwvoogt** [liprec/vsts-release-aas#58]
Power BI Premium has XMLA End-point Read/Write capabilities. You can use TMSL-scripts to update the tabular models. I would like to use this extention in Devops to automate execution of TMSL against my Power BI Premium-workspace. I tried but it seems this only works with Azure Analyis Service.

![image](https://user-images.githubusercontent.com/55580355/119628310-44059180-be0d-11eb-9c72-8bdac4446623.png)

Is it possible to use the extention with Power BI Premium? Would love it when this can be added...

**Comment by liprec** [comment]
AFAIK the current PoSh modules do not work with PBI Premium as there are some differences between the two services.
My long time goal is to extend this task to support PBI Premium.
