### ISSUE TITLE
Unable to connect to China AAS via Azure DevOps

### ISSUE THREAD

**Issue by meghapayal** [liprec/vsts-release-aas#59]
We are using the Analysis service task to deploy model into AAS. It is working for all regions, but when trying to deploy model to AAS china region it is failing with the below error.

**Unknown Analysis Services environment name specified.**
Analysis service name is "asazure://chinaeast2.asazure.chinacloudapi.cn/edpcndevdwana"

Also, we are using a azure china cloud service connection for the deployment.
Some screenshots for reference.

Error Log:
![image](https://user-images.githubusercontent.com/54704002/121149575-68775a00-c860-11eb-97af-cddac36cc29d.png)

Service connection used:
![image](https://user-images.githubusercontent.com/54704002/121149716-85ac2880-c860-11eb-903e-3ea2b4782354.png)

**Comment by liprec** [comment]
Thanks for the feedback and I will look into this: I will update the client libraries ad PoSh modules and hopefully this will also solve this issue. Problem is that I cannot test it myself...
