### ISSUE TITLE
We were unable to deploy model using  deploy Azure App services in vsts

### ISSUE THREAD

**Issue by padmavathicse** [liprec/vsts-release-aas#6]
Hi Team,

We were facing some issues while deploying the model /API using azure app service.

Kindly help me on this.

Thanks,
Padma,
7829535553.

**Comment by padmavathicse** [comment]
![azure issue](https://user-images.githubusercontent.com/29402464/37828484-6b6fa762-2ec1-11e8-9ab0-77c2a5e4680c.png)

**Comment by padmavathicse** [comment]
please provide the information for this

**Comment by liprec** [comment]
Look like the Azure Analysis Service throws an error was causes the 'operation was canceled'.
You can try to enable the debug mode for the  release by adding the variable `system.debug` and set it to `true`. This provides more information and hopefully a clue to the real problem.

**Comment by liprec** [comment]
Will close the issue for now. If this is still an issue, please reopen the issue and provide the requested information.
