### ISSUE TITLE
Analysis Services client libraries older

### ISSUE THREAD

**Issue by youyou0625** [liprec/vsts-release-aas#60]
i received from Microsoft this message after deploy :

Analysis Services client libraries version 19.12.3.0 or higher, offers important security enhancements, so any applications that are still using earlier versions of the Analysis Services client libraries will not be supported after 30 June 2021. 
Action required 
To minimize risk and potential security vulnerabilities, please update your Analysis Services client libraries to version 19.12.3.0 or higher before 30 June 2021. 
https://docs.microsoft.com/en-us/analysis-services/client-libraries?view=asallproducts-allversions#check-installed-versions

**Comment by liprec** [comment]
Thanks and it looks like I need to (minimal) upgrade the client libraries.

**Comment by liprec** [comment]
Just checked my self, but I cannot find any reference to an old AS client in the extension. Are you using a self-hosted agent? If zo, you need to update the Analysis Service client libraries yourself on the agent.
Or can you share a (extended) log so I can take another look?

Thanks.
