### ISSUE TITLE
Deployment of analysis service model Not deploying the correct model 

### ISSUE THREAD

**Issue by prateekmanochakwc** [liprec/vsts-release-aas#61]
Hi, I am using Azure CD pipeline to deploy my azure analysis service model via task "Deploy model" from azure devops. The deployment goes successful but the Model name comes as  'Model' while my file says Sapphire.bim and the same Sapphire is being passed as Model Name parameter too. Can you please help me here ?

**Comment by liprec** [comment]
The name of the `.bim` file is not used in the script to rename the model, but the parameter `modelName` should be used to rename the model before deployment. Do you see any errors/warnings during deployment? And if you enable the debug option (`system.debug = true`)?

**Comment by prateekmanochakwc** [comment]
Hi Jan,

Thanks for reaching out to me.

I can attach the logs for you I could not find any such warning and indeed the parameter Model Name carries the value "Sapphire for me"

We can also arrange a call if you like!

Please find attached the log s for the deployment.

BR,
Prateek

**Comment by liprec** [comment]
Hi @prateekmanochakwc,

Due to the email reply I do not see the attached log file. Can you either upload it to the GitHub issue or email it directly to me: mail@datascenarios.nl ?

**Comment by prateekmanochakwc** [comment]
Hi Jan,

I have replied to your email and sent an attachment via below mentioned Email Address.

Awaiting to hear from you .

BR,
Prateek
