### ISSUE TITLE
TMSL deployment of roles from DevOps pipeline failure

### ISSUE THREAD

**Issue by RoelEvers** [liprec/vsts-release-aas#66]
Hi,
today we noticed that our TMSL scripts that we have been using to deploy our analysis services model roles ( createorreplace command ) no longer work in our release pipelines in devops.
The error we get is:

2022-01-03T10:33:19.7528525Z ##[error]Error during executing queries (Execute TMSL against '***' complete with errors.

The System.Object[] text node at line 7, column 31 cannot appear inside the Command element (namespace urn:schemas-microsoft-com:xml-analysis) under Envelope/Body/Execute. This element can only have text nodes containing white-space characters.

The error seems to refer to XMLA scripting judging by the namespace. 

Any idea why this would happen ? We have been deploying our models this way for quit some time now.

Regards
   Roel

**Comment by liprec** [comment]
The extension has updated recently and that is the reason of this different behavior.
Can you share the TMSL script (structure) you are using? And also which options?

*And btw with the updated the deploy task got the options to retain roles and/or membership during deployment*

**Comment by RoelEvers** [comment]
[Model_Readers.txt](https://github.com/liprec/vsts-release-aas/files/7801590/Model_Readers.txt)

We are using the Folder with TMSL files option.
We noticed the new features as well.

**Comment by liprec** [comment]
This issue is fixed in version v1.5.1which will be available anytime soon.

**Comment by RoelEvers** [comment]
We just tested the fix and it seems to be working again. Thanks you for the very fast response !
