### ISSUE TITLE
Object names in AAS models like measures containing special characters are displayed incorrectly in PowerBI after deployment

### ISSUE THREAD

**Issue by RoelEvers** [liprec/vsts-release-aas#68]
When manually deploying the model from Visual Studio the object name ( f.e. Efficiëntie ) is displayed correctly in the report. However, when deployed through the release pipe line the special characters are not. Looks like some sort of code page problem.

Could this have anything to do with the latest updates ?

Regards
   Roel

**Comment by liprec** [comment]
Sorry about this, but indeed loading the model was missing the UTF8 encoding flag.
Is now fixed in version 1.5.2
