### ISSUE TITLE
Error when 'remove before deploy' is checked

### ISSUE THREAD

**Issue by simplesi** [liprec/vsts-release-aas#7]
Thanks for the extension, which is mostly working well for me.

When I check 'remove before deploy', I get:
```Error during deploying the model (The property 'database' cannot be found on this object. Verify that the property exists and can be set.)```

I can do this by using a TMSL script, but it would be nicer to have just one step.

**Comment by liprec** [comment]
Probably this is due to the same reason as issue #8: the compatibility level of the model is 1200 and that is not yet supported in this extension.

**Comment by liprec** [comment]
Will close the issue for now. If this is still an issue, please reopen the issue and provide the requested information.
