### ISSUE TITLE
AAS deployment Error during detecting agent IP address

### ISSUE THREAD

**Issue by mmikos** [liprec/vsts-release-aas#71]
After the update we seem to have a problem with deployment of analysis services database. 
We're logging in through a named used with a managed account. Everything was working properly before but now we're getting this error:

_Error during detecting agent IP address (Exception calling "Connect" with "1" argument(s): "Unable to obtain authentication token using the credentials provided. If your Active Directory tenant administrator has configured Multi-Factor Authentication or if your account is a Microsoft Account, please remove the user name and password from the connection string, and then retry. You should then be prompted to enter your credentials.")_

Would you mind looking into this?

We checked that username and password is correct and all the other necessary pipeline variables.
Here are the logs: 
[log_pipeline.txt](https://github.com/liprec/vsts-release-aas/files/7806967/log_pipeline.txt)

**Comment by liprec** [comment]
The new version is using the credentials of the service connection for all Azure activities, including adding and removing the firewall rules. The named user is only used to connect to the AAS instance. 
Is it possible to configure the SPN of the service connection to add `contribute` rights to the AAS resource?

**Comment by mmikos** [comment]
For the service connection we already have configured a service principle with contributor rights to aas.

**Comment by Patrickva** [comment]
We're experiencing the same issue. If I can provide you with any information regarding the issue please let me know. Our SPN has full security rights on the AAS resource.

**Comment by liprec** [comment]
Sorry, was misjudging what was causing this, but it is indeed caused on how to the named user is passed to the AAS. I will submit an update anytime soon.

For the easy way forward, you use the `inherit` option to drop the named user. But for that you have to add the SPN as Analysis Services Admins.

**Comment by liprec** [comment]
The extension had been updated to version 1.5.3 and will be available anytime soon.

**Comment by mmikos** [comment]
The bug has been resolved for Tabular Database Deployment, however I'm still getting a similar message for the TMSL script.

**Comment by liprec** [comment]
Version v1.5.3 of the TMSL task contains the same fix. Probably you are hitting a cached version of the task; my experience is when you rerun the pipeline the latest version of the task will be used.

**Comment by Patrickva** [comment]
Thanks, for the quick respond. On our side everything is working again.
