### ISSUE TITLE
AAS Deployment Datasource Connection

### ISSUE THREAD

**Issue by svboca** [liprec/vsts-release-aas#72]
Hi, After the update the option to update the datasource conection is not working properly. The option Azure SQL (Single connection) is not updating the datasource. The model I m using has only one SQL connection. As a fix I m using the TSML script task to createOrReplace the datasource.

**Comment by liprec** [comment]
thanks fort he feedback, but this is an duplicate of #70 and will be fixed in an upcoming update.
I will close this issue as it is a duplicate.

**Comment by liprec** [comment]
The extension had been updated to version 1.5.3 and will be available anytime soon.
