### ISSUE TITLE
AAS deployment failing

### ISSUE THREAD

**Issue by Silpa-Suresh** [liprec/vsts-release-aas#73]
The model.bim file doesn't contain data source details. We were providing the details through the Azure DevOps task inputs, since we have multiple environments. Now we are getting the following error on trying the deployment without any changes to model.bim file:

### The JSON DDL request failed with the following error: Failed to execute XMLA. Error returned: 'M Engine error: 'Microsoft.Data.Mashup; <pii>The given data source reference is not a valid data source.</pii>'.
'..

@liprec , Could you please help in understanding the solution to the above error?

**Comment by liprec** [comment]
Can you share the debug log (variable: `System.Debug` set to `true`) to provide me some more details?
And also the `yml` with the datasource connection details?

**Comment by Silpa-Suresh** [comment]
[task.txt](https://github.com/liprec/vsts-release-aas/files/7807640/task.txt)
[tasklog_7.log](https://github.com/liprec/vsts-release-aas/files/7807928/tasklog_7.log)

Attached yml and log file. 

Tried the option of advanced datasource setting as mentioned in: https://github.com/liprec/vsts-release-aas/issues/70#issuecomment-1004617259

Still getting same error.

**Comment by liprec** [comment]
Can you try running the pipeline again? And check if the deploy task is version 1.5.3?
That version should have an extra check regarding the data source input and hopefully solves this problem.

**Comment by Silpa-Suresh** [comment]
Great, It worked now. Thanks a lot.
