### ISSUE TITLE
AAS deployment [error]Invalid JSON primitive: xYef5BbaPG.

### ISSUE THREAD

**Issue by svboca** [liprec/vsts-release-aas#75]
Since the last update (version 1.5.3) AAS deployment fails with the error: [error]Invalid JSON primitive: xYef5BbaPG

**Comment by liprec** [comment]
Can you share the debug log (variable: System.Debug set to true) to provide me some more details?

**Comment by svboca** [comment]
[tasklog_8.log](https://github.com/liprec/vsts-release-aas/files/7808604/tasklog_8.log)

**Comment by liprec** [comment]
Looking at your options, it looks like the password is not enclosed with quotes (`"`) and probably causing this issue.
Can you try adding double quotes around your password? And make sure your password doesn't contain any quotes (`'`, `"`)

**Comment by svboca** [comment]
Thank you for the prompt reply. This morning I tested the advanced Data Source Type. Now I understand that the security setting should be a 'valid' statement, despite using the None Data Source Type.

So I replaced it with the original value:

[
  {
    "name": "<DataSourceName>",
    "authenticationKind": "UsernamePassword",
    "connectionDetails": {
      "address": {
        "server": "<ServerName>",
        "database": "<DatabaseName>"
      }
    },
    "credential": {
      "Username": "<UserName>",
      "Password": "<Password>"
    }
  }
]

It now runs all fine!

**Comment by liprec** [comment]
Indeed the task is not looking at the `connectionType` option anymore. Probably it is better to add this check again to minimize this kind of issues.
