### ISSUE TITLE
Unable to obtain authentication token using the credentials provided

### ISSUE THREAD

**Issue by NickelBronze** [liprec/vsts-release-aas#76]
My steps to execute XMLA no longer work, it's getting the following error.

_Error connecting to tabular service. (Exception calling "Connect" with "1" argument(s): "Unable to obtain authentication token using the credentials provided. If your Active Directory tenant administrator has configured Multi-Factor Authentication or if your account is a Microsoft Account, please remove the user name and password from the connection string, and then retry. You should then be prompted to enter your credentials.")_

I tried deleting the step and re-creating it.  Quadruple checked the credentials.

Any advice?

**Comment by NickelBronze** [comment]
I'm able to deploy the model using the same credentials, no issues.

**Comment by NickelBronze** [comment]
![image](https://user-images.githubusercontent.com/53919161/148289955-fcc0f0cd-1671-4063-9b71-7cfb7ea7b1ce.png)
I noticed the following after the update.

The Service Connection Type selected is 'connectedServiceNameARM'.  But when I click the drop down list, the only options are 'Azure Resource Manager' and 'Power BI'.

When looking at the log, I see that 'connectedServiceNameARM' is still chosen, even though I've selected 'Azure Resource Manager' (screen shot is of another release pipeline I didn't try fixing yet)
[log.txt](https://github.com/liprec/vsts-release-aas/files/7817837/log.txt)
.

**Comment by liprec** [comment]
The connection type has an new option (Power BI) and therefor I renamed the existing option. But it is only the 'friendly name' and not the option value itself: that is still `connectedServiceNameARM`

But indeed this is a (simple) bug: I forgot to update the task version, so it is still using a cached (old) version in your pipeline 🤦. Will update the version and release a new version.

**Comment by liprec** [comment]
The extension is updated to version 1.5.4 and will be available anytime soon.
