### ISSUE TITLE
Lost inline TMSL content after bugfix

### ISSUE THREAD

**Issue by trondis80** [liprec/vsts-release-aas#78]
Hi and thanks for creating and managing a great tool!

We are using the Analysis Services deployment task for lots of stuff. We noticed that after your latest release our inline TMSL scripts were gone. I see in your code (execute-aas-tmsl/v1/task.json) that you did a renaming of tsmlScript to tmslScript. I suspect that this is why the content disappeared. We also needed to set a few other parameters.

We were able to go to the task history and recover the code.

Just wanted to let you know in case other people has this problem, or if you are considering future versioning strategies or "backward compatibility".

Cheers,
Trond

**Comment by liprec** [comment]
Sorry to hear that, but the `tmslScript` option does have the old (incorrect) `tsmlScript` as alias. To my understanding this should cover the old options.
Is it possible to share the task `yml` and log (with `System.Debug` set to `true`) of the failed run, so I can take a look why it is not working as expected?

**Comment by trondis80** [comment]
It wasn't a failed run, the (classic) pipeline editor showed those red warnings "some settings need attention" (see image below) and the pipeline could therefore not be run or saved.

![image](https://user-images.githubusercontent.com/63094829/148396700-7cae8aec-a99b-4770-8453-b009dfb7bdb1.png)

We needed to reconfigure service connection, database name and the inline TMSL scripts before we were able to run the pipelines.

Like I said, we got it to work after these adjustments.

**Comment by liprec** [comment]
Thanks for the feedback, but probably I have to fiddle with the variables again as the current configuration gives some strange behavior. But I am thinking about moving the inputs to a different section in the UI, so at least you are not missing the information.

**Comment by liprec** [comment]
In the latest update I have updated the inputs (again) and now the old inputs are now part of the `Deprecated inputs` section so you can copy-paste those to the correct values when you are ready.
The task only warns when the old values are being used, but still completes are expected.

**Comment by trondis80** [comment]
Thanks, I got the update this morning:-) I couple of observations:

* I had to reconfigure the Service Connection setting for all the tasks.
* The Deprecated Inputs are empty, I expected the old values here (perhaps updating yesterday removed the values though...)

![image](https://user-images.githubusercontent.com/63094829/148522935-be50d956-1bb4-40f4-a956-edd083c23c19.png)

**Comment by liprec** [comment]
Indeed probably the updates you did yesterday had already the expected result.
And sorry about the service connections: I had to change those also, but unfortunately this kind of changes seems to have a huge impact on the classic UI.
Hope that everything is now running as expected.

**Comment by trondis80** [comment]
Everything is good, thanks again for a wonderful tool!

**Comment by liprec** [comment]
Closing the issue and feel free to open a new issue if you have feedback in the future.
