### ISSUE TITLE
can't use variable for [Analysis Services URL]

### ISSUE THREAD

**Issue by mdc17** [liprec/vsts-release-aas#79]
By using a variable to determinant [Analysis Services URL] we get an error

![image](https://user-images.githubusercontent.com/27221028/148382704-db977c88-dc11-4ecd-b578-0e458da01a53.png)

![image](https://user-images.githubusercontent.com/27221028/148382598-5e7eb6cb-708c-4149-a0a3-00bf91d08151.png)

It's only working by palace the server URL as text

**Comment by liprec** [comment]
Can you share the debug log (variable: System.Debug set to true) to provide me some more details?

**Comment by mdc17** [comment]
Server URL is asazure://centralus.asazure.windows.net/asMMMMtest001 

Please check the log

[tasklog_6.log](https://github.com/liprec/vsts-release-aas/files/7822015/tasklog_6.log)

**Comment by liprec** [comment]
Looking at the logging it seems that the SPN of the Service Connection doesn't have enough rights to 'see' the AAS.
In the new version the SPN should at least have contributor rights to add/remove the firewall.

**Comment by mdc17** [comment]
Are trim the variable value? I realized that there was a space at the end of the URL. Can you check this?

**Comment by liprec** [comment]
The space indeed looks like the issue as the logs are showing the extra space at the end. And no the tasks assumes that you have provided the correct server name, but a trim left/right will add some extra usability.
