### ISSUE TITLE
[error]Unrecognized escape sequence. (531)

### ISSUE THREAD

**Issue by benoit-aa** [liprec/vsts-release-aas#83]
Hi,

Since recently, I get the following error (it was working before).
Not sure if related but the password contains the character \

![image](https://user-images.githubusercontent.com/87364583/148745204-b3351296-8bc2-4fb7-a74d-93f2559c1277.png)

Benoit

**Comment by liprec** [comment]
Seems to me like that is causing this escaping issue as the base for the task is PowerShell. Is it possible to change the `\` in the password? Or use a (new) dedicated user/password combination without any special character?

**Comment by benoit-aa** [comment]
This is a bug. We deployed hundred of customers with passwords always containing special characters, we cannot change this easily without huge impact to our whole landscape and configuration.

This is only happening since the recent updates (with which we already had lots of issues and losing our in-line scripts, connection services several times).

Btw, is there a way to use the version before 1.5.x until this is fixed ?

**Comment by liprec** [comment]
I have updated the task (v1.5.6) to escape the SQL Password value.

**Comment by benoit-aa** [comment]
FYI, we tried it today and it worked for the password containing \ (version used was 1.5.7).
We did not test with other special characters (I see some still have issues in the other thread).
