### ISSUE TITLE
 v1.5.6 we are getting an error: Unrecognized escape sequence.

### ISSUE THREAD

**Issue by sikalokym** [liprec/vsts-release-aas#85]
Hello
after v1.5.6 we are getting an error: Unrecognized escape sequence.
If our password contains '#' mark it is converted like 'test#' -> 'test\\#' and does not work, means raises an error: Unrecognized escape sequence.

**Comment by sikalokym** [comment]
Seems to be working fine now.
Thanks for quick turnaround.

**Comment by MikaAhosilta** [comment]
Hi, 

We're still getting the same error with version 1.5.7 so it looks like there are still issues with the escaping. These are all the special characters included in my password: %';|~**`

![Devops_Error](https://user-images.githubusercontent.com/26243449/148938484-6a2aeb7b-8fb7-48b2-98ba-aacc4f65fcaf.png)
+

**Comment by liprec** [comment]
@MikaAhosilta: a new version is rolled out (v.1.5.8) which should work with all your special characters: `` %';|~**` ``

**Comment by MikaAhosilta** [comment]
Now it's working again. Thanks for your help!
