### ISSUE TITLE
AAS deployment - SQL DB Connection Security Settings not updated

### ISSUE THREAD

**Issue by benoit-aa** [liprec/vsts-release-aas#88]
Hello,

Since 1.5.x, I noticed that the Security Settings are not updated and are referencing our development system (DEV) even when we deploy to our quality system (QAS).
I'm not sure what is the impact of this because the Connection Details are OK.

Since 1.5.x, "path" referencing DEV server and DEV model (bug):

![image](https://user-images.githubusercontent.com/87364583/148955992-34be2e9d-d823-467b-b142-99ae01073104.png)

Before 1.5.x, "path" referencing QAS server (OK) and no model (OK):

![image](https://user-images.githubusercontent.com/87364583/148956426-2ad64250-b913-47a6-8fa2-6c68a2e139ad.png)

Please advise.

Thanks,
Benoit

**Comment by liprec** [comment]
The `path` property is not used by the connection itself and as you are saying: the connection is fine. Myself I have no idea what the `path` property is doing, but I noticed that there is no need to update it, so in the 1.5.x version I left is as-is.
