### ISSUE TITLE
TMSL Script error

### ISSUE THREAD

**Issue by TrailRunner23** [liprec/vsts-release-aas#90]
Hi, I am getting this error, ##[error] System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.

This is using task TMSL Script in Azure DevOps.

Can you maybe assist.

**Comment by liprec** [comment]
Can you share the pipeline logging with the variable `System.Debug` set to `true`?

**Comment by TrailRunner23** [comment]
[log.txt](https://github.com/liprec/vsts-release-aas/files/7915199/log.txt)

Please find attached the log of the last run with the error

**Comment by liprec** [comment]
Thanks for the logging. It seems that getting an access token with the credentials of the service connection is raising the error.

Can you validate that the service connection is able to connect to Azure?
