### ISSUE TITLE
Pipeline error after upgrade?

### ISSUE THREAD

**Issue by GolamRashed** [liprec/vsts-release-aas#92]
We set up our pipeline in 2020 with this repo, then it got updated recently to v1.5.8 and there are two new fields that were not present in the previous v1.3.6. How can we select the values for these two drop-down menu items so that our workflow is not impacted (stays like v1.3.6)?

![MicrosoftTeams-image](https://user-images.githubusercontent.com/1528712/150779460-e8d4a87f-a5b4-4a60-bb47-c3e8a9a92bdc.png)

**Comment by liprec** [comment]
The default values are: `Deploy partitions (deploypartitions)` and `Deploy roles and members (deployrolesandmembers)`

**Comment by GolamRashed** [comment]
Thanks for the quick reply. These default values will not affect our existing data?

**Comment by liprec** [comment]
These values will overwrite the target partitions and roles including memberships, same as the previous versions.
If you want to preserve target/service partitions, you can alter the option to `retainpartitions`. Same is for the roles and members.

**Comment by liprec** [comment]
Yes
