### ISSUE TITLE
No resource found with serverName "Server", serverType Microsoft.AnalysisServices/servers in subscription "Subscription Name" Specify the correct serverName/serverType and try again.

### ISSUE THREAD

**Issue by dyogesh95** [liprec/vsts-release-aas#96]
Hello,

I am trying to deploy tabular model using this task. There are no issues till Jan 2022 but somewhere in middle it says
"No resource found with serverName "Server", serverType Microsoft.AnalysisServices/servers in subscription "Subscription Name" Specify the correct serverName/serverType and try again."

All the connections and properties looks good like
1. A Service connection is created to the resource group using SPN and the connection is successful
2. The SPN has contributor access on resource group
3. The App created is added as an admin in analysis service and
4. I am able to connect to the same the server from my machine
Am I missing something ?

**Comment by liprec** [comment]
The things I can image are that the Azure Analysis Service is not in the resource group provided, the SPN doesn't have contributor rights at the Azure Analysis Service level, or that you made a typo.
Make sure that the AAS is in the correct resource group and subscription. The current version is using this hierarchy to interact with the firewall and if something is misconfigured, the task will fail with the above error.

**Comment by nixuwixu** [comment]
I have the same issue did you find any solution @dyogesh95 ?

**Comment by liprec** [comment]
@nixuwixu, did you check if the given resource group contains the Azure Analysis Service? And that the SPN have minimal contributor rights to the Azure Analysis Service?

**Comment by nixuwixu** [comment]
@liprec  It works now, I had to create a new ServiceProvider on the subscription that had the AS, somehow the previous version ( 1.3 )worked with a RnD ServiceProvider we had.
