### ISSUE TITLE
System.Net.WebException. The remote name could not be resolved.

### ISSUE THREAD

**Issue by yeykawb** [liprec/vsts-release-aas#97]
Hi Jan Pieter.

So, I've been using this extension for some time without issues.
However just now this error came from nowhere. Any clues to what it could be?

`##[error]System.Net.WebException: The remote name could not be resolved: 'management.azure.com'
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
`

![Snag_1a0d114](https://user-images.githubusercontent.com/97282358/158198515-41e56b6d-3238-4cd4-88e0-80dbf33e7c7f.png)

**Comment by liprec** [comment]
Looks like the agent does have a connection issue as it cannot resolve the `management.azure.com`. Can you validate that the agent does have valid internet connection?

**Comment by yeykawb** [comment]
I can validate that it did work when running the pipeline today instead, so most probably this was the cause. I just wanted to make sure the issue wasn't on my side.
Thanks for the reply!
/ Jakob
