### ISSUE TITLE
Error connecting to tabular service. (Exception calling "Connect" with "1" argument(s): "Failed to resolve PBI workspace. Description:

### ISSUE THREAD

**Issue by SeanMuggin** [liprec/vsts-release-aas#99]
I have had an admin set up my xmla endpoint set up for read/write and all other necessary configuration described here [https://github.com/TabularEditor/tabulareditor.github.io/blob/master/_posts/2020-06-02-PBI-SP-Access.md#enable-service-principal-api-access](url) for setting up a Service Principal. Filled in all necessary information in the Power Platform service connection. I have not set up the SP or anything else in the actual Power Platform portal. I could reach out to an admin if that is necessary but I don't have access to that.

This is a TestDB with a skeleton model and no data source.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/38870781/158461954-e6b9699c-e16c-4187-a156-9ca4e27fc08d.png">

<img width="579" alt="image" src="https://user-images.githubusercontent.com/38870781/158462138-d837fa7a-fe3c-4245-8342-00bb551c4d34.png">

<img width="245" alt="image" src="https://user-images.githubusercontent.com/38870781/158462710-f1af4a0e-4311-47ca-9bb6-cb9d570e5086.png">

**Comment by liprec** [comment]
Please make sure that you also add the SP to the workspace ad Member or Admin.
See for more info: [https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-service-principal#workspace-access](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-service-principal#workspace-access?WT.mc_id=DP-MVP-5003419)

**Comment by SeanMuggin** [comment]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/38870781/158465084-7b4ce1c8-1d2f-4c19-a7e2-f0a0b1e95309.png">

Are you referring to the PowerBI workspace or the Power Platform workspace? I have the SP included in the DevOpsSG security group which is included as an Admin in the PowerBI workspace

**Comment by liprec** [comment]
If that is the workspace that is 'behind' the XMLA endpoint that that part is correct. Can you connect to the XMLA endpoint with SSMS and the SP?

**Comment by SeanMuggin** [comment]
I have been using Tabular Editor v 2.16.5 to test my xmla connections and I can indeed make a successful connection and even a successful deployment using the same xmla endpoint. The difference with Tabular Editor GUI is that it uses a UI popup for credentials instead of the SP

**Comment by liprec** [comment]
I have no experience with Tabular Editor, but can you try to connect with username: `app:<appId>@<tenantid>` and as password the SP secret? And replace `<appid>` and `<tenantid>` with the correct guids.

**Comment by SeanMuggin** [comment]
Probably worth mentioning my first attempt at CI/CD was using the Tabular Editor workflow and I get the same error when trying to make a CLI deployment. I have tried to isolate my issue by using multiple different tabular models/ workspaces and creating a fresh tabular models and fresh DB but always get the same result. I go into detail of my deployment attempts with tabular editor in this github issue here : https://github.com/TabularEditor/TabularEditor/issues/972

**Comment by SeanMuggin** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/38870781/158467674-88dfe418-f846-47a1-9d2d-b2dd358fa57b.png">

Exact error I have been receiving when trying to use the SP

**Comment by SeanMuggin** [comment]
Is there an alternate CLI command or authorization I can try using User credentials instead of Service Principal to confirm it is the Service Principal that is causing the issue? I have already done successful deployments using the XMLA endpoint using the user credentials of the Admin account DevOps that you see in the Workspace Access screenshot above so I may have already proven that point. 

At least Tabular Editor doesn't like when I try and replace User Id= and Password= with my user credentials instead of SP creds
<img width="307" alt="image" src="https://user-images.githubusercontent.com/38870781/158468846-84a0d8d6-3220-4c97-b344-25e5ea7c88a9.png">

**Comment by liprec** [comment]
Can you try using the 'Username and Password' authentication option of TE to login?
And to make sure that all the basics are correct: the XMLA endpoint is correct and have a Premium or PPU license assigned?

**Comment by SeanMuggin** [comment]
<img width="368" alt="image" src="https://user-images.githubusercontent.com/38870781/158470380-ee95c256-e067-4b8e-9316-3f6109f831b1.png">
This works

**Comment by liprec** [comment]
Can you make sure that the secret doesn't contain any quotes (single or double)?
PowerShell does have issues with those and needs escaping, so the uncomplicated way is to go with a secret without.

**Comment by SeanMuggin** [comment]
No quotes. The only symbols my secret contains are '.' and '~'

**Comment by liprec** [comment]
Is it possible to run the pipeline with `system.debug` set to `true` and share the `debug.log` file?

**Comment by SeanMuggin** [comment]
I'll look into that now

**Comment by SeanMuggin** [comment]
I can post the text directly if you would prefer not to download but it is lengthy

[tasklog_9.log](https://github.com/liprec/vsts-release-aas/files/8257223/tasklog_9.log)

**Comment by SeanMuggin** [comment]
The last line I see output in the logs from deploy-aas-db.ps1 is 
  Write-Verbose "Loading database '$databaseName' from '$aasServer'"
  So I think it must be failing on line 171
  
$currentDatabase, $server = LoadTabularDatabaseFromServer -server $aasServer -database $databaseName -credential $credential

**Comment by SeanMuggin** [comment]
I got it to work by switching the login type to "Named user" which I guess can work temporarily but says it will be deprecated soon. I am fairly certain I have gone through every necessary step to set up the Service Principal correctly but there must be something unique with my deployment environment that is not allowing the Service Principal to connect to the workspace.

**Comment by SeanMuggin** [comment]
Reached out to admin who set up the Service Principal and confirmed they accidently assigned my user account to the Security Group instead of the Service Principal which is why it was working with "Named user" instead of the inherited Service Principal from the Service Connection.
